name:                llvm-test-example
version:             1.0.0.0

dependencies:
  - base
  - llvm-hs

library:
  source-dirs:      src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wnoncanonical-monad-instances
    - -Wnoncanonical-monadfail-instances

